spring:
  application:
    name: auth-demo
  security:
    user:
      name: admin
      password: admin
      roles: user
server:
  port: 8080
  servlet:
    context-path: /demo/v1
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  pattern:
    console: