spring:
  application:
    name: auth-demo
  security:
    user:
      name: admin
      password: admin
      roles: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:dbtest
    username: root
    password: 123456
    driverClassName: org.h2.Driver
    settings:
      web-allow-others: true
  thymeleaf:
    cache: false
  sql.init.platform: h2
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: ${api-key}
      chat:
        options:
          model: deepseek-chat
server:
  port: 8080
  servlet:
    context-path: /demo/v1
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info