spring:
  application:
    name: auth-demo
  security:
    user:
      name: admin
      password: admin
      roles: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://${mysql.host}:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: ${mysql.password}
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  sql.init.platform: mysql
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: ${api-key}
      chat:
        options:
          model: deepseek-chat
  output:
    ansi:
      enabled: always
  data:
    jdbc:
      dialect: mysql
server:
  port: 8080
  servlet:
    context-path: /demo/v1
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info